#------------------------------------------------------------------------------
# VARIABLES
#------------------------------------------------------------------------------
# Variables specified in this file can be used in the documentation via:
#     {{ site.CONFIG_KEY }}
#------------------------------------------------------------------------------

FLINK_VERSION_STABLE: 0.5.1
FLINK_VERSION_STABLE_SHORT: 0.5.1
FLINK_GITHUB_TAG_STABLE: release-0.5.1

FLINK_VERSION_LATEST: 0.6-SNAPSHOT
FLINK_VERSION_LATEST_SHORT: 0.6
FLINK_GITHUB_TAG_LATEST: master

FLINK_ISSUES_URL: https://issues.apache.org/jira/browse/FLINK
FLINK_GITHUB_URL: https://github.com/apache/incubator-flink
FLINK_GITHUB_REPO_NAME: incubator-flink

FLINK_DOWNLOAD_URL_HADOOP_1_STABLE: https://github.com/stratosphere/stratosphere/releases/download/release-0.5.1/stratosphere-bin-0.5.1.tgz
FLINK_DOWNLOAD_URL_HADOOP_2_STABLE: https://github.com/stratosphere/stratosphere/releases/download/release-0.5.1/stratosphere-bin-0.5.1-hadoop2.tgz
FLINK_DOWNLOAD_URL_YARN_STABLE: https://github.com/stratosphere/stratosphere/releases/download/release-0.5.1/stratosphere-bin-0.5.1-yarn.tar.gz

FLINK_DOWNLOAD_URL_HADOOP_1_LATEST: http://stratosphere-bin.s3-website-us-east-1.amazonaws.com/stratosphere-0.6-SNAPSHOT.tgz
FLINK_DOWNLOAD_URL_HADOOP_2_LATEST: http://stratosphere-bin.s3-website-us-east-1.amazonaws.com/stratosphere-0.6-hadoop2-SNAPSHOT.tgz
FLINK_DOWNLOAD_URL_YARN_LATEST: http://stratosphere-bin.s3-website-us-east-1.amazonaws.com/stratosphere-dist-0.6-SNAPSHOT-yarn.tar.gz

baseurl: /incubator-flink-website

#------------------------------------------------------------------------------
# BUILD CONFIG
#------------------------------------------------------------------------------
# These variables configure the jekyll build (./build_docs.sh). You don't need
# to change anything here.
#------------------------------------------------------------------------------

defaults:
  -
    scope:
      path: ""
    values:
      layout: default

  -
    scope:
      path: "docs"
    values:
      layout: docs

highlighter: pygments
markdown: redcarpet
redcarpet:
  # https://help.github.com/articles/github-flavored-markdown
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink",
               "tables", "with_toc_data", "strikethrough", "superscript",
               "lax_spacing"]

# News Posts
paginate: 10
paginate_path: "news/page:num"